---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build-app
    taskRef:
      name: mvn-build
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: source
        resource: app-git
  - name: build-image
    taskRef:
      name: buildah
    params:
    - name: DOCKERFILE
      value: Dockerfile.openjdk
    - name: TLSVERIFY
      value: "false"
    resources:
      inputs:
      - name: source
        resource: app-git
        from: [build-app]
      outputs:
      - name: image
        resource: app-image
