---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: operator-deploy-pipelinerun-
spec:
  serviceAccount: pipeline
  pipelineRef:
    name: deploy-pipeline
  resources:
  - name: app-git
    resourceRef:
      name: mapit-git
  - name: app-image
    resourceRef:
      name: mapit-image
